// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoppinglist.Data;

#nullable disable

namespace Shoppinglist.Data.Migrations
{
    [DbContext(typeof(ShoppingListDbContext))]
    partial class ShoppingListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Shoppinglist.Data.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Shoppinglist.Data.Models.Recipie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipies");
                });

            modelBuilder.Entity("Shoppinglist.Data.Models.RecipieItem", b =>
                {
                    b.Property<int>("RecipieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipieId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("RecipieItems");
                });

            modelBuilder.Entity("Shoppinglist.Data.Models.RecipieItem", b =>
                {
                    b.HasOne("Shoppinglist.Data.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoppinglist.Data.Models.Recipie", "Recipie")
                        .WithMany("RecipieItems")
                        .HasForeignKey("RecipieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Recipie");
                });

            modelBuilder.Entity("Shoppinglist.Data.Models.Recipie", b =>
                {
                    b.Navigation("RecipieItems");
                });
#pragma warning restore 612, 618
        }
    }
}
